name: unicode fix
description: idk just got it from Fatal

runs:
 using: composite
 steps:
  - name: apply unicode fix for specific kernel version
    shell: bash
    run: |
     cd "$COMMON"
     echo "detected kernel version: $KERNEL_VERSION"

     if [[ $KERNEL_VERSION == 6.* ]]; then
      cp "$KERNEL_PATCHES/common/unicode_bypass_fix_6.1+.patch" .
      patch -p1 < unicode_bypass_fix_6.1+.patch
     else
      cp "$KERNEL_PATCHES/common/unicode_bypass_fix_6.1-.patch" .
      patch -p1 < unicode_bypass_fix_6.1-.patch
     fi
