name: add IP-set and ipv6NET support
description: literally what above said

runs:
 using: composite
 steps:
  - name: add ip-set and ipv6_NAT support in defconfig and apply patch
    shell: bash
    run: |

     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_MAX=65534"
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_BITMAP_IP
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_BITMAP_IPMAC
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_BITMAP_PORT
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_IP
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_IPMARK
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_IPPORT
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_IPPORTIP
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_IPPORTNET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_IPMAC
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_MAC
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_NETPORTNET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_NET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_NETNET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_NETPORT
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_HASH_NETIFACE
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_SET_LIST_SET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NETFILTER_XT_MATCH_ADDRTYPE
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NETFILTER_XT_SET
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP6_NF_NAT
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP6_NF_TARGET_MASQUERADE

     cd "$COMMON"
     patch -p1 < "$KERNEL_PATCHES/common/IPv6_NAT_FIX.patch"
