name: set variables
description: set environment variables

runs:
 using: composite
 steps:
  - name: set dependency directory variables
    shell: bash
    run: |
     ROOT="$GITHUB_WORKSPACE"
     ANYKERNEL3="$ROOT/AnyKernel3"
     KERNEL_PATCHES="$ROOT/kernel_patches"
     echo "ROOT=$ROOT" >> $GITHUB_ENV
     echo "ANYKERNEL3=$ANYKERNEL3" >> $GITHUB_ENV
     echo "KERNEL_PATCHES=$KERNEL_PATCHES" >> $GITHUB_ENV
     
  - name: set common variable
    shell: bash
    run: |
     if [[ $BRANCH == SM-A546* || "$BRANCH" == "SM-M146B-Oneui7-ADYJ2" || "$BRANCH" == "SM-S908B-Oneui8-bitK" || $BRANCH == SM-X610* || "$BRANCH" == "SM-A166B-Oneui7" || "$BRANCH" == "SM-A356E-Oneui8" ]]; then  
       COMMON="$CONFIG"
     elif [[ "$BRANCH" == "SM-A566B" || $BRANCH == SM-A055* ]]; then
       COMMON="$CONFIG/kernel-6.6"
     elif [[ $BRANCH == SM-S926B* || $BRANCH == SM-A556* ]]; then
       COMMON="$CONFIG/kernel"
     elif [[ "$BRANCH" == "SM-A075M-Oneui7" ]]; then
       COMMON="$CONFIG/kernel-5.10"
     elif [[ "$BRANCH" == "SM-X926B-Oneui6.1" ]]; then
       COMMON="$CONFIG/kernel-6.1"
     else
       COMMON="$CONFIG/kernel_platform/common"
     fi
     echo "COMMON=$COMMON" >> $GITHUB_ENV
    
  - name: set defconfig variable
    shell: bash
    run: |
     if [[ $BRANCH == SM-A546B* ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-a54xnaxx_defconfig"
     elif [[ $BRANCH == SM-A546E* ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-a54xnsxx_defconfig"
     elif [[ "$BRANCH" == "SM-M146B-Oneui7-ADYJ2" ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8535-m14xnsxx_defconfig"
     elif [[ "$BRANCH" == "SM-S908B-Oneui8-bitK" ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e9925-b0sxxx_defconfig"
     elif [[ $BRANCH == SM-X610* ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-gts9fepwifixx_defconfig"
     elif [[ "$BRANCH" == "SM-A166B-Oneui7" ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8535-a16xxx_defconfig"
     elif [[ "$BRANCH" == "SM-A356E-Oneui8" ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-a35xjvxx_defconfig"
     else
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/gki_defconfig"
     fi
     echo "GKI_DEFCONFIG=$GKI_DEFCONFIG" >> $GITHUB_ENV
