name: add configs
description: add configs and disabling securities
inputs:
 branch:
   description: 'which device kernel'
   required: true

runs:
 using: composite
 steps:
  - name: add mountify support
    shell: bash
    run: |
     cat >> "$GKI_DEFCONFIG" << 'EOF'
     # Mountify Support
     CONFIG_OVERLAY_FS=y
     CONFIG_TMPFS_XATTR=y
     CONFIG_TMPFS_POSIX_ACL=y
     EOF
     
  - name: nuke securities for root access
    shell: bash
    run: |
     # 1. Determine which defconfig file needs to be patched based on the branch
     target_config=""
     
     if [[ ${{ inputs.branch }} == SM-S938B* || "${{ inputs.branch }}" == "SM-S931B-Oneui8" ]]; then
         echo "Nothing to see here, moving on..."
     elif [[ "${{ inputs.branch }}" == SM-S926B* ]]; then
         target_config="$COMMON/arch/arm64/configs/s5e9945-bazel_defconfig"
     elif [[ "${{ inputs.branch }}" == SM-A556* ]]; then
         target_config="$COMMON/arch/arm64/configs/s5e8845-bazel_defconfig"
     else
         target_config="$GKI_DEFCONFIG"
     fi
     
     # 2. Apply the nuke modifications exactly once if a target file was assigned
     if [ -n "$target_config" ]; then
      echo "Nuking Samsung Knox/Root protection in: $target_config"

     
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_UH
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_UH_RKP
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_UH_LKMAUTH
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_UH_LKM_BLOCK
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_RKP
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_RKP_CFP_JOPP
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_RKP_CFP_ROPP
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_RKP_CFP
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_SECURITY_DEFEX
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_PROCA
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_FIVE
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_KDP
     "$COMMON/scripts/config" --file "$target_config" --disable CONFIG_KDP_NS
     fi

  - name: remove check_defconfig
    shell: bash
    run: |
     cd "$COMMON"
     # Remove check_defconfig
     sed -i 's/check_defconfig//' ./build.config.gki
