name: add configs for ubuntu-chroot
description: same as above


runs:
 using: composite
 steps:
  - name: add configs for ubuntu-chroot
    shell: bash
    run: |
     cat >> "$GKI_DEFCONFIG" << EOF
     CONFIG_NAMESPACES=y
     CONFIG_PID_NS=y
     CONFIG_UTS_NS=y
     CONFIG_MNT_NS=y
     CONFIG_IPC_NS=y
     CONFIG_DEVTMPFS=y
     CONFIG_PROC_FS=y
     CONFIG_SYSFS=y
     CONFIG_BINFMT_MISC=y
     CONFIG_BINFMT_SCRIPT=y
     CONFIG_BINFMT_ELF=y
     CONFIG_SYSVIPC=y
     CONFIG_SYSVIPC_SYSCTL=y
     CONFIG_PROC_SYSCTL=y
     CONFIG_POSIX_MQUEUE=y
     CONFIG_CGROUPS=y
     CONFIG_CGROUP_DEVICE=y
     CONFIG_MEMCG=y
     EOF
