name: add bbrv3 AND bbrv1
description: enable configs to add bbrv3 and v1 to kernel

runs:
 using: composite
 steps:
  - name: apply bbrv3 patch
    shell: bash
    run: |
     cd "$COMMON"
     patch -p1 < "$KERNEL_PATCHES/common/bbrv3/0001-net-tcp-backport-BBRv3-to-$ANDROID_VERSION-$KERNEL_VERSION.patch"
     
  - name: add bbr configs to defconfig
    shell: bash
    run: |
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NET_SCH_FQ
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NET_SCH_FQ_CODEL
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NET_SCH_CAKE
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NET_SCH_PIE
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NET_SCH_FQ_PIE
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_TCP_CONG_ADVANCED
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_TCP_CONG_BBR
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_TCP_CONG_BBR3
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_TCP_CONG_CUBIC
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --disable CONFIG_TCP_CONG_BIC
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --disable CONFIG_TCP_CONG_WESTWOOD
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --disable CONFIG_TCP_CONG_HTCP
