name: parse branch
description: parse branch names for cache keys

runs:
 using: composite
 steps:
  - name: parse cache keys
    shell: bash
    run: |
        FULL_BRANCH="$BRANCH"
        echo "FULL_BRANCH=$FULL_BRANCH" >> $GITHUB_ENV
           
        BASE_BRANCH=$(echo "$FULL_BRANCH" | sed -E 's/(-bit[0-9]+.*$)|(-bit.*$)//i')
        echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

