name: enable LTO
description: samsung seems to have no LTO in their kernels, this enables it

runs:
 using: composite
 steps:
  - name: enable FULL LTO
    shell: bash
    run: |
     cd "$COMMON"
     sed -i '/^default LTO_NONE$/s/default LTO_NONE/default LTO_CLANG_FULL/' arch/Kconfig
