name: add ntsync
description: integrate ntsync into kernel

runs:
  using: composite
  steps:
   - name: apply ntsync patches
     shell: bash
     run: |
      cd "$COMMON"
      patch -p1 < "$KERNEL_PATCHES/common/ntsync/ntsync_base.patch"
      patch -p1 < "$KERNEL_PATCHES/common/ntsync/ntsync_compat_$ANDROID_VER-$KERNEL_VER.patch"
      
   - name: enable ntsync config
     shell: bash
     run: |
      "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_NTSYNC

