name: add TTL support
description: same as above

runs:
 using: composite
 steps:
  - name: apply ttl support
    shell: bash
    run: |
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP_NF_TARGET_TTL
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP6_NF_TARGET_HL
     "$COMMON/scripts/config" --file "$GKI_DEFCONFIG" --enable CONFIG_IP6_NF_MATCH_HL
