name: add TTL support
description: same as above

runs:
 using: composite
 steps:
  - name: apply ttl support
    shell: bash
    run: |
     config=(
     "CONFIG_IP_NF_TARGET_TTL=y"
     "CONFIG_IP6_NF_TARGET_HL=y"
     "CONFIG_IP6_NF_MATCH_HL=y"
     )

     for config in "${configs[@]}"; do
         key="${config%%=*}"

         if grep -qE "^(${key}=|# ${key} is not set$)" "$GKI_DEFCONFIG"; then
             sed -i -E \
                 -e "s/^${key}=.*/${config}/" \
                 -e "s/^# ${key} is not set\$/${config}/" \
                 "$GKI_DEFCONFIG"
         else
             echo "$config" >> "$GKI_DEFCONFIG"
         fi
     done
